print("Hi Python")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa----------------LOUISA")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa        ^")
print("My Name is Louisa       / \\")
print("My Name is Louisa       | |")
print("My Name is Louisa       | |")
print("My Name is Louisa       | |")
print("My Name is Louisa       ---")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa")

print("My Name is Louisa----------------LOUISA")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa        ^")
print("My Name is Louisa       / \\")
print("My Name is Louisa       | |")
print("My Name is Louisa       | |")
print("My Name is Louisa       | |")
print("My Name is Louisa       ---")

print("My Name is Louisa----------------LOUISA")
print("My Name is Louisa")
print("My Name is Louisa")
print("My Name is Louisa        ^")
print("My Name is Louisa       / \\")
print("My Name is Louisa       | |")
print("My Name is Louisa       | |")
print("My Name is Louisa       | |")
print("My Name is Louisa       ---")



